planner:
  env_type: 1 # 0 for 2D, 1 for 3D
  size_of_cropped_pointcloud: [6, 6, 3]
  goal_z_pos: 0.5

  # Parameters for robot shape
  # robot_shape/points: [0.1, 0.1, 0.1,
  #                      0.1, -0.1, 0.1,
  #                     -0.1, -0.1, 0.1,
  #                     -0.1, 0.1, 0.1,
  #                      0.1, 0.1, -0.1,
  #                      0.1, -0.1, -0.1,
  #                     -0.1, -0.1, -0.1,
  #                     -0.1, 0.1, -0.1]
  # robot_shape/imu_pos: [0.0, 0.0, 0.0]

  robot_shape/points: [0.1, 0.1,
                       0.1, -0.1,
                      -0.1, -0.1,
                      -0.1, 0.1]
  robot_shape/imu_pos: [0.0, 0.0]

  # Parameters for lidar
  lidar/min_elev_angle: -30.67    # degrees
  lidar/max_elev_angle: 20.67     # degrees

  # Parameters for gap extractor for 3D environment
  gap_extractor/3D/min_pixels_in_open_gap_region: 20
  gap_extractor/3D/open_gap_yaw_span: 0.7854  # 45 degrees
  gap_extractor/3D/open_gap_elev_span: 0.3491  # 20 degrees
  gap_extractor/3D/min_pixels_in_subregion: 40
  gap_extractor/3D/range_map_width: 1600  # lidar horizontal resolution
  gap_extractor/3D/range_map_height: 32  # lidar vertical resolution
  gap_extractor/3D/map_size: 3 # meters
  gap_extractor/3D/yaw_split_threshold_in_limited_gap_region: 0.5236 # 30 degrees
  gap_extractor/3D/elev_split_threshold_in_limited_gap_region: 0.3491 # 20 degrees
  gap_extractor/3D/min_pixels_in_limited_gap_region: 48
  gap_extractor/3D/limited_gap_yaw_span: 0.5236 # 30 degrees
  gap_extractor/3D/limited_gap_elev_span: 0.5236 # 30 degrees
  gap_extractor/3D/min_pixels_in_limited_subregion: 32

  # Parameters for gap extractor for 2D environment
  gap_extractor/2D/min_pixels_in_open_gap_region: 10
  gap_extractor/2D/open_gap_yaw_span: 0.7854  # 45 degrees
  gap_extractor/2D/min_pixels_in_subregion: 20
  gap_extractor/2D/range_map_width: 1600  # lidar horizontal resolution
  gap_extractor/2D/range_map_height: 1  # lidar vertical resolution
  gap_extractor/2D/map_size: 3 # meters
  gap_extractor/2D/yaw_split_threshold_in_limited_gap_region: 0.5236 # 30 degrees
  gap_extractor/2D/elev_split_threshold_in_limited_gap_region: 0.3491 # 20 degrees
  gap_extractor/2D/min_pixels_in_limited_gap_region: 2
  gap_extractor/2D/limited_gap_yaw_span: 0.5236 # 30 degrees
  gap_extractor/2D/limited_gap_elev_span: 0.5236 # 30 degrees
  gap_extractor/2D/min_pixels_in_limited_subregion: 2

  # Parameters for yaw/elev adjustment in limited gap region
  gap_extractor/limited_gap_bias_yaw: 0.1746 # 10 degrees
  gap_extractor/limited_gap_bias_elev: 0.1746 # 10 degrees