planner:
  env_type: 1 # 0 for 2D, 1 for 3D
  size_of_cropped_pointcloud: [6, 6, 3]

  # Parameters for interesting direction extraction
  direction_extractor/num_of_edge_pts_: 20
  direction_extractor/curvature_threshold_: 0.8
  direction_extractor/num_of_neighbors_to_cluster_: 10 # better to be even number, since we will search half on each side
  direction_extractor/clustering_distance_threshold_: 0.2 # meters

  # Parameters for goal in 3D
  direction_extractor/goal_z_: 0.0
  direction_extractor/goal_roll_: 0.0
  direction_extractor/goal_pitch_: 0.0

  # Parameters for gap extractor
  gap_extractor/min_pixels_in_open_gap_region: 20
  gap_extractor/open_gap_yaw_span: 0.7854  # 45 degrees
  gap_extractor/open_gap_elev_span: 0.3491  # 20 degrees
  gap_extractor/min_pixels_in_subregion: 40
  gap_extractor/range_map_width: 1600  # lidar horizontal resolution
  gap_extractor/range_map_height: 32  # lidar vertical resolution
  gap_extractor/map_size: 3 # meters
  gap_extractor/yaw_split_threshold_in_limited_gap_region: 0.5236 # 30 degrees
  gap_extractor/elev_split_threshold_in_limited_gap_region: 0.3491 # 20 degrees
  gap_extractor/min_pixels_in_limited_gap_region: 48
  gap_extractor/limited_gap_yaw_span: 0.5236 # 30 degrees
  gap_extractor/limited_gap_elev_span: 0.5236 # 30 degrees
  gap_extractor/min_pixels_in_limited_subregion: 32
