planner:
  env_type: 1 # 0 for 2D, 1 for 3D
  size_of_cropped_pointcloud: [6, 6, 3]

  # Parameters for interesting direction extraction
  direction_extractor/num_of_edge_pts_: 20
  direction_extractor/curvature_threshold_: 0.8
  direction_extractor/num_of_neighbors_to_cluster_: 10 # better to be even number, since we will search half on each side
  direction_extractor/clustering_distance_threshold_: 0.2 # meters

  # Parameters for goal in 3D
  direction_extractor/goal_z_: 0.0
  direction_extractor/goal_roll_: 0.0
  direction_extractor/goal_pitch_: 0.0

  # Parameters for gap extractor
  gap_extractor/yaw_split_threshold: 0.5235987756 # 30
  gap_extractor/elev_split_threshold: 0.2617993878 # 15
  gap_extractor/min_pixels_in_open_gap_region: 20
  gap_extractor/range_map_width: 1600  # lidar horizontal resolution
  gap_extractor/range_map_height: 32  # lidar vertical resolution
  gap_extractor/map_size: 5 # meters